# Generated by Django 5.2.3 on 2025-07-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('po_number', models.CharField(max_length=100, verbose_name='Contract / P.O No')),
                ('client', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('po_description', models.TextField()),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budgetary_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_drawing', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComponentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('material_procurement', models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20)),
                ('fabrication', models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20)),
                ('hdg', models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20, verbose_name='HDG')),
                ('powder_coating', models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20)),
                ('erection', models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='ongoing_projects.ongoingproject')),
            ],
        ),
    ]
