# Generated by Django 5.2.3 on 2025-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoing_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingproject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
