# Generated by Django 5.2.3 on 2025-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoing_projects', '0002_ongoingproject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingproject',
            name='status',
            field=models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='In Progress', max_length=20),
        ),
    ]
