# Generated by Django 5.2.3 on 2025-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoing_projects', '0003_ongoingproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponentstatus',
            name='hdg',
            field=models.CharField(choices=[('N/A', 'N/A'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='N/A', max_length=20),
        ),
    ]
