# Generated by Django 5.2.3 on 2025-07-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0003_remove_deliverynote_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='branch',
            field=models.CharField(default='Steel Department', max_length=100),
        ),
    ]
