# Generated by Django 5.2.3 on 2025-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0004_deliverynote_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='contract_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='supply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
