# Generated by Django 5.2.3 on 2025-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0005_deliverynote_client_name_deliverynote_contract_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='total_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
