# Generated by Django 5.2.3 on 2025-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0007_deliveryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='total_remarks',
        ),
    ]
