# Generated by Django 5.2.3 on 2025-07-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0009_remove_deliverynote_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='so_number',
        ),
    ]
