# Generated by Django 5.2.3 on 2025-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0010_remove_deliveryitem_so_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
