# Generated by Django 5.2.3 on 2025-07-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0011_deliverynote_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMaterialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ref_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supply_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_notes.incomingmaterialreport')),
            ],
        ),
    ]
