# Generated by Django 5.2.3 on 2025-07-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0012_incomingmaterialreport_incomingmaterialitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomingMaterialItem',
        ),
        migrations.DeleteModel(
            name='IncomingMaterialReport',
        ),
    ]
